# JVM memory
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8 -XX:+UseParallelGC

# AndroidX
android.useAndroidX=true

# Only keep R classes for the current module
android.nonTransitiveRClass=true

# Enable Gradle configuration cache for faster builds
org.gradle.configuration-cache=true
org.gradle.parallel=true
org.gradle.caching=true
